### ISSUE TITLE
Component inside <Transition> renders non-element root node that cannot be animated. 

### ISSUE THREAD

**Issue by 209** [element-plus/element-plus-nuxt-starter#11]
https://github.com/209/element-plus-nuxt-starter

  ```
<el-dropdown>
    <span>
      test
    </span>
    <template #dropdown>
      <div>
        <el-dropdown-menu>
          <el-dropdown-item>Action 1</el-dropdown-item>
          <el-dropdown-item>Action 2</el-dropdown-item>
          <el-dropdown-item>Action 3</el-dropdown-item>
          <el-dropdown-item disabled>Action 4</el-dropdown-item>
          <el-dropdown-item divided>Action 5</el-dropdown-item>
        </el-dropdown-menu>
      </div>
    </template>
  </el-dropdown>
```

<img width="524" alt="Снимок экрана 2021-10-24 в 01 12 37" src="https://user-images.githubusercontent.com/4629854/138573182-dd2ce804-f73e-4864-83aa-4ff95996c3fe.png">

If add root `<div>` then we haven't warn

**Comment by iamanewofkotlin** [comment]
Its seems like ``el-dropdown`` is not single dom. so you should wrapper it by ``div``

**Comment by xiaoxian521** [comment]
fix: https://github.com/element-plus/element-plus-nuxt-starter/commit/98aa178d5031359d67653e1b5f5f7611ab94ca1f
