### ISSUE TITLE
Table with header, SSR

### ISSUE THREAD

**Issue by 209** [element-plus/element-plus-nuxt-starter#12]
https://github.com/209/element-plus-nuxt-starter
```
    <el-table
        :data="tableData"
        style="width: 100%"
        :stripe="true"
        :fit="true"
        :sortable="false"
        :show-header="true"
    >
      <el-table-column prop="field" label="Field" width="180" />
      <el-table-column prop="value" label="Value" width="180" />
    </el-table>
```

<img width="534" alt="Снимок экрана 2021-10-24 в 01 32 13" src="https://user-images.githubusercontent.com/4629854/138573562-c6e4837c-3c4d-47a8-813f-2283719ab639.png">

In SSR we have "0" in html before hydrate. 
We haven't problem with `:show-header="false"`

upd: Table doesn't render on server :(
Only after hydrate

**Comment by xiaoxian521** [comment]
looks normal
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/44761321/154970373-7fade810-5e10-47a9-aae5-97ae0b8b354d.png">
