### ISSUE TITLE
build报错

### ISSUE THREAD

**Issue by hzm18** [element-plus/element-plus-nuxt-starter#13]
执行命令`yarn build`报错：
yarn版本：1.22.10
node版本：16.11.1
npm版本：8.1.0
系统：archlinux
`
 ERROR  Could not resolve './use-prevent-globalThis' from ./use-prevent-globalThis?commonjs-external                        21:02:42

 ERROR  Could not resolve './use-prevent-globalThis' from ./use-prevent-globalThis?commonjs-external                        21:02:42

  at error (node_modules/rollup/dist/shared/rollup.js:158:30)
  at ModuleLoader.handleResolveId (node_modules/rollup/dist/shared/rollup.js:22263:24)
  at node_modules/rollup/dist/shared/rollup.js:22257:26

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by Johnson-hd** [comment]
+1

**Comment by Johnson-hd** [comment]
@YunYouJun Nuxt3有相关issue嘛？

**Comment by YunYouJun** [comment]
See here. https://github.com/nuxt/framework/issues/1006

**Comment by Johnson-hd** [comment]
@YunYouJun thx！

**Comment by YunYouJun** [comment]
Now, it works by upgrade nuxt3!
