### ISSUE TITLE
Another option is displayed in Select Component

### ISSUE THREAD

**Issue by takimotoSE** [element-plus/element-plus-nuxt-starter#14]
Hi, element-plus-nuxt-starter team!
I'm using Element-plus with Nuxt3.
That's where I encountered the problem in the issue title.

In the code, they are separate components, but each option is displayed together as shown in the image.
![スクリーンショット 2021-11-02 18 25 22](https://user-images.githubusercontent.com/39073920/139820763-99e7ef16-2e3e-4167-9c5b-d56a0abf1f2f.png)
<img width="468" alt="スクリーンショット 2021-11-02 17 38 57" src="https://user-images.githubusercontent.com/39073920/139820800-66209b58-857a-49b5-be0f-4a5c990ba843.png">
<img width="468" alt="スクリーンショット 2021-11-02 17 39 03" src="https://user-images.githubusercontent.com/39073920/139820817-5a445e5b-9b37-4093-8acb-ad493c3e43ad.png">

I just added the code to this repository, is this a problem with the way it is written?
Or is this a problem in the Nuxt3 situation?😔

Please advise🙇

**Comment by YunYouJun** [comment]
Can you provide a minimum reproducible repo? Thanks.

**Comment by takimotoSE** [comment]
OK! 
I will provide pull request.

**Comment by takimotoSE** [comment]
Resolved this isuue!!!
I developed it with SSR, but I solved it by changing it to CSR😃
Thanks.
