### ISSUE TITLE
How use ``unplugin-vue-components/vite`` with ``nuxt3``?

### ISSUE THREAD

**Issue by iamanewofkotlin** [element-plus/element-plus-nuxt-starter#15]
How use ``unplugin-vue-components/vite`` with ``nuxt3``?

We need on-demand import.

**Comment by YunYouJun** [comment]
Yeah, we are exploring this.

https://github.com/nuxt/components#library-authors

But `@nuxt/components` seems not support `components/ComponentA/index.js`. It may take some time to resolve.

**Comment by Cabbages** [comment]
I solve the problem through the following configuration：`nuxt.config.ts`
```js
import { defineNuxtConfig } from "nuxt3";
import { join } from "path";

export default defineNuxtConfig({
  meta: {
    title: "ElementPlus + Nuxt3",
  },
  css: ["assets/scss/index.scss"],
  components: [
    "~/components",
    {
      path: join(__dirname, "node_modules/element-plus/lib/components"),
      pattern: ["*/index.js"],
      prefix: "el",
    },
  ],
});

```

**Comment by xiaoxian521** [comment]
refer to: https://github.com/element-plus/element-plus-nuxt-starter/commit/98aa178d5031359d67653e1b5f5f7611ab94ca1f
