### ISSUE TITLE
Can not use css

### ISSUE THREAD

**Issue by alanhzw** [element-plus/element-plus-nuxt-starter#18]
the button's color is #ffffff

![image](https://user-images.githubusercontent.com/41323555/146111632-e809159c-f870-4ee2-9475-4a689f9e7e67.png)

**Comment by polly3d** [comment]
Same issue here.

**Comment by YunYouJun** [comment]
element-plus still can not work well with nuxt3. And nuxt3 still being updated and have not yet been released stavle version.

Please just wait.

**Comment by calebeaires** [comment]
@YunYouJun, it is true, but may you give us a clue of what is missing so we can try to make some progress?

**Comment by YunYouJun** [comment]
@calebeaires Sorry, I don't know why too.

**Comment by calebeaires** [comment]
Make it work using client only wrapper

```vue
<template>
  <main>
    <ClientOnly>
      <NuxtPage />
    </ClientOnly>
  </main>
</template>

```

I think the way Element-plus set ccs variables in the button html is not compatible with the "rendering server time"!

**Comment by xiaoxian521** [comment]
This will be resolved in the next version of element-plus

**Comment by xiaoxian521** [comment]
try:
`
  <client-only>
        <el-button type="primary">test</el-button>
  </client-only>
`

**Comment by estudiooka** [comment]
+1 Same here since the first release of element-plus. Inline styles are not inject with SSR.
Client only is not a realiable solution.

**Comment by estudiooka** [comment]
Also to make it compatible with nuxt should be an option to render the button as a nuxt-link component.

**Comment by xiaoxian521** [comment]
> Also to make it compatible with nuxt should be an option to render the button as a nuxt-link component.

This issue has been resolved, upgrade `element-plus` to the latest version
