### ISSUE TITLE
在nuxt3 服务器渲染Popover组件会出现多个Popover都显示同一个弹窗内容问题 而且有时候在服务器还会报错

### ISSUE THREAD

**Issue by Morii120** [element-plus/element-plus-nuxt-starter#23]
![image](https://user-images.githubusercontent.com/13359932/156312994-95896fa4-4bfa-4538-a767-166e2d94d518.png)

**Comment by lubaihong** [comment]
还原bug 只需要 在这个项目新建一个页面 在页面使用el-popover el-select 标准就可以了
