### ISSUE TITLE
能写一个在nuxt3中引入element-plus的自定义主题例子吗？

### ISSUE THREAD

**Issue by KahrLu** [element-plus/element-plus-nuxt-starter#25]
看了element-plus的自定义主题文档，和nuxt3的文档，比较模糊，谢谢了！

**Comment by YunYouJun** [comment]
Nuxt3 仍在 beta 阶段，暂时还并不可用，且 Nuxt 通常部分模块的使用方式有所区别，短时间不会着重在此方面的适配。

**Comment by KujoMiva** [comment]
> Nuxt3 仍在 beta 阶段，暂时还并不可用，且 Nuxt 通常部分模块的使用方式有所区别，短时间不会着重在此方面的适配。

已经提交了自定义主题的PR

**Comment by 798714773** [comment]
https://stackoverflow.com/questions/75027997/how-to-configure-nuxt-3-element-plus-ui-with-scss

**Comment by YunYouJun** [comment]
已增加了自定义主题示例与更多组件效果预览。
