### ISSUE TITLE
el-dropdown bug ，The former frame data is overwritten by the latter data.

### ISSUE THREAD

**Issue by whm-applesin** [element-plus/element-plus-nuxt-starter#27]
![image](https://user-images.githubusercontent.com/103315685/162572191-0b231acf-db07-40b0-bc06-58803074d8bd.png)
![image](https://user-images.githubusercontent.com/103315685/162572279-4804f19b-7f95-423b-9916-56062c79c151.png)
![image](https://user-images.githubusercontent.com/103315685/162572338-3304e8a2-534a-43b6-bdb4-87f184a2876f.png)

element-plus > el-dropdown > el-dropdown-menu 。  The former frame data is overwritten by the latter data. This is the latest version, nothing has changed，only the two el-dropdown .

**Comment by JiatLn** [comment]
el-menu组件的el-sub-menu 下拉亦是如此 有解决方案吗

**Comment by YunYouJun** [comment]
I think it is caused by ssr.

Just use `<client-only></client-only>` wrap your dropdown. And it works.
