### ISSUE TITLE
Element 能在nuxt3中全量引入吗？包括Elmessage,Elcomfirm

### ISSUE THREAD

**Issue by LY-Net** [element-plus/element-plus-nuxt-starter#29]

**Comment by YunYouJun** [comment]
可以。

**Comment by moonwaystudio** [comment]
怎么引入法

**Comment by moonwaystudio** [comment]
> 可以。

怎么引入法

**Comment by YunYouJun** [comment]
你可以参考 nuxt 文档获取 vueApp。

https://nuxt.com/docs/api/composables/use-nuxt-app#vueapp

随后在 app.vue 中正常全量引入即可。

https://element-plus.org/zh-CN/guide/quickstart.html#%E5%AE%8C%E6%95%B4%E5%BC%95%E5%85%A5

未经测试的一个简要示意：

```ts
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'

nuxtApp.vueApp.use(ElementPlus)
```
