### ISSUE TITLE
Can share a example with `unplugin-vue-components`?

### ISSUE THREAD

**Issue by chris-zhu** [element-plus/element-plus-nuxt-starter#30]
When I try it on my local environment, I get the following error. 

> env: { "nuxt": "^3.0.0-rc.3", "element-plus": "^2.2.0", }

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/42139754/168064773-210b9f18-cf3e-479c-8d23-974136c8efa4.png">

**Comment by chris-zhu** [comment]
Well, i mean auto import element-plus components, rather than manually importing.

Interestingly, I found this in the documentation. ( [Nuxt3 docs aboout componets library](https://v3.nuxtjs.org/guide/directory-structure/components/#library-authors) )

**Comment by sxzz** [comment]
Hmmm i see, nuxt3 doesn't support custom resolver yet.

**Comment by chris-zhu** [comment]
I'm guessing the same, although I've tried multiple things locally with no success. 

I will keep watching.
