### ISSUE TITLE
500 Cannot set properties of undefined (setting 'pinia')

### ISSUE THREAD

**Issue by Messent** [element-plus/element-plus-nuxt-starter#43]
![image](https://user-images.githubusercontent.com/22971679/179720488-a06f0b78-04aa-4b1a-ade0-f5068cc7d156.png)
fix: "@pinia/nuxt": "^0.1.9",=>"@pinia/nuxt": "^0.3.0",

**Comment by Messent** [comment]
Nuxt3 RC5 & RC6

**Comment by leosin** [comment]
![image](https://user-images.githubusercontent.com/3676670/180050752-18f242bd-b386-4a31-ac77-62852bb2767a.png)
