### ISSUE TITLE
nuxt3.rc-8引入element-plus2.2.13报错

### ISSUE THREAD

**Issue by KahrLu** [element-plus/element-plus-nuxt-starter#46]
nuxt3升级到rc-8就没法引入element-plus了。rc-7和rc-8升级了vite到vite3，不知道是哪边的原因 ，另外这个starter项目可以适配一下nuxt3最新的预览版吗？作为一个升级到vite3的阶段性版本，nuxt3已经接近于发正式版了。请适配一下，现在还是nuxt.rc-3
![image](https://user-images.githubusercontent.com/76502123/185527640-fc5e8b18-2144-4503-8e18-f9fdc0399ed0.png)
![image](https://user-images.githubusercontent.com/76502123/185527725-cae36a7d-44a3-4b15-83df-53e43d191749.png)

**Comment by YunYouJun** [comment]
也许和 Vite 3 有关，出于时间精力，我们希望可以在 Nuxt RC 结束后，一次性完成适配。

当然 PR 也是完全欢迎的。

**Comment by sxzz** [comment]
请参考最新模板。
