### ISSUE TITLE
About  `typescript`  question? Does this need to be installed again?

### ISSUE THREAD

**Issue by RSS1102** [element-plus/element-plus-nuxt-starter#48]
Does this need to be installed again?
1. It says "nuxt 3 is fully typed and provides helpful shortcuts to ensure you have access to accurate type information when you are coding".https://v3.nuxtjs.org/guide/concepts/typescript。

2.I do not install `typescript`, but I still have type verification.
![image](https://user-images.githubusercontent.com/81673017/187251240-58afabf7-2b13-4169-ac42-8c2630f87512.png)
![image](https://user-images.githubusercontent.com/81673017/187251279-925cbf0e-09f8-4aef-bcb7-a9fd9a1f9059.png)

**Comment by YunYouJun** [comment]
You should write it like this `let name: string | number = '123'`.

By the way, `String` shoud be 'string'.

**Comment by RSS1102** [comment]
> You should write it like this `let name: string | number = '123'`.
> 
> By the way, `String` shoud be 'string'.

OK,This is my mistake. My main question is to ask the difference between installing `typescript `and not.

The above figure is just to prove that I have not installed `typescript `, and I can still make type judgment.
**I don't quite understand the difference between whether to install or not.**(To determine if I want to install `typescript `as well)
thanks.

**Comment by YunYouJun** [comment]
If you install `typescript`, you can control the version of typescript.

If you do not install it, it will invoke global typescript or a version of typescript invoked by another package.

If you don't want typescript type check, write it like this:

```html
<script setup>
// just remove lang="ts" in script
</script>
```

**Comment by RSS1102** [comment]
> 

ok,Thank you very much for your answer.
