### ISSUE TITLE
Override SCSS variables doesn't work

### ISSUE THREAD

**Issue by nphungthinh2601** [element-plus/element-plus-nuxt-starter#52]
https://element-plus.org/en-US/guide/theming.html#by-scss-variables
https://stackoverflow.com/questions/72512042/how-to-change-colors-of-a-tempa-element-plus-in-nuxt3
It doesn't work.

**Comment by YunYouJun** [comment]
Check example?

**Comment by sokphengkean** [comment]
Hello, is there any solution for that? 
I face the same problem too.
