### ISSUE TITLE
示例demo在执行完yarn install后运行build，generate等会报错，dev不会报错

### ISSUE THREAD

**Issue by chencu5958** [element-plus/element-plus-nuxt-starter#58]
如上述标题所述，我在github codespace下执行yarn install安装好依赖后，执行build,generate等都会出现例如这样的报错
，使用dev就正常，排查后怀疑是nuxt3.1.x和elementplus有兼容性问题，将nuxt版本锁定在3.0.0则正常无报错，在锁定版本测试时仅将package.json里有关nuxt的依赖版本从"^3.0.0"修改为了"~3.0.0"或"3.0.0"，别的均未修改

ℹ Initializing prerenderer 

 ERROR  Error: Could not load raw:element-plus/theme-chalk/el-icon.css (imported by node_modules/element-plus/es/components/icon/style/css.mjs): ENOENT: no such file or directory, open 'element-plus/theme-chalk/el-icon.css'

undefined

 ERROR  Could not load raw:element-plus/theme-chalk/el-icon.css (imported by node_modules/element-plus/es/components/icon/style/css.mjs): ENOENT: no such file or directory, open 'element-plus/theme-chalk/el-icon.css'

**Comment by chencu5958** [comment]
发现这个问题的原因也是因为我在另外一个使用Nuxt3+Element Plus的项目里也遇到了相同的情况，只能是锁定了Nuxt3的版本号，要不然到了Initializing prerenderer这步就指定会报错

**Comment by tolking** [comment]
[Link](https://github.com/element-plus/element-plus-nuxt/pull/30) 

This issue has been fixed and we will release a new version for `@element-plus/nuxt` in the near future.

**Comment by tolking** [comment]
A new version for @element-plus/nuxt has been release, Please update to the latest version (1.0.3).

**Comment by chencu5958** [comment]
> A new version for @element-plus/nuxt has been release, Please update to the latest version (1.0.3).

可以正常用了，感谢
