### ISSUE TITLE
求助：动态组件如何正确使用，是否不支持动态组件渲染

### ISSUE THREAD

**Issue by OSpoon** [element-plus/element-plus-nuxt-starter#62]
求助：动态组件如何正确使用，是否不支持动态组件渲染

我想通过读取路由配置渲染icon，为什么动态组件没有生效
```typescript
<el-menu-item v-for="route in routes" :index="route.path" @click="toPage(route.path)">
   <el-icon color="#409EFC" class="no-inherit">
    <component :is="route?.mate?.icon" />
   </el-icon>
</el-menu-item>
```

相同的下面直接使用对应的icon是正常的
```typescript
<el-menu-item v-for="route in routes" :index="route.path" @click="toPage(route.path)">
   <el-icon color="#409EFC" class="no-inherit">
      <el-icon-histogram />
   </el-icon>
   <span>{{route?.mate?.name}}</span>
</el-menu-item>
```

![image](https://user-images.githubusercontent.com/10126623/224919230-72d7743f-27eb-46f1-a31b-c1abee109cce.png)

**Comment by jw-foss** [comment]
.. 动态组件的前提是，你直接传入组件的 Object 或者是你的这个组件要在全局注册，

- `<component :is="" />` 内部调用 `resolveComponent` 方法去获取组件，当你的组件没有注册的情况下，通过 string 作为参数是没有办法能够 resolve 出来任何东西的。

请仔细阅读 [Vue 文档](https://vuejs.org)。

还有一个事情，劳烦提问的时候给足上下文，你目前给出的代码并不足以让我们能够帮助到你去 debug，这样的提问是无效的。

尽量把你相关的代码全部提上来。谢谢。

**Comment by jw-foss** [comment]
@OSpoon 确实是可以使用组件名字的，这一点我在上面也进行了回复

> <component :is="" /> 内部调用 resolveComponent 方法去获取组件，当你的组件没有注册的情况下，通过 string 作为参数是没有办法能够 resolve 出来任何东西的。

在你给到的复制品里也能够看到： 

![CleanShot 2023-03-14 at 15 26 27@2x](https://user-images.githubusercontent.com/15975785/224926198-840cc344-eca5-48f6-ad1c-e09620a7aaf4.png)

这个组件是没有渲染的。

**Comment by jw-foss** [comment]
@OSpoon Vue 的这个能成功因为这是被正确注册的组件，Nuxt 注册的方式跟这个不太一样，`<component />` 是一个特殊的组件，就像我上面说的内部用了 `resolveComponent` 来实现，所以在这里他并没有办法来获取到。
