### ISSUE TITLE
SSR Preview: 500 Cannot find package '@popperjs/core'

### ISSUE THREAD

**Issue by KeJunMao** [element-plus/element-plus-nuxt-starter#66]
https://element-plus-nuxt.vercel.app/

links:
- https://github.com/element-plus/element-plus/issues/10979
- https://github.com/nuxt/nuxt/issues/14930

**Comment by lmq352489099** [comment]
+1  @sxzz

**Comment by YunYouJun** [comment]
See https://vercel.com/docs/frameworks/nuxt#edge-functions, i add `NITRO_PRESET=vercel-edge`, and it works well now.

**Comment by uestcNaldo** [comment]
实测，最后改成了yarn包管理器就可以了（部署平台是RK3588的边缘盒子）
