### ISSUE TITLE
upgrading to the latest 

### ISSUE THREAD

**Issue by guipie** [element-plus/element-plus-nuxt-starter#73]
After upgrading to the latest version, the home page is refreshed repeatedly every time it is loaded, which is very slow

![image](https://github.com/element-plus/element-plus-nuxt-starter/assets/55727172/2ecaf5f7-df05-4033-84f6-1781a13fef44)

**Comment by YunYouJun** [comment]
Try the new dependencies? I can't reproduce your problem.
