### ISSUE TITLE
引入全局样式优先级会低于elementPlus，有什么方法可以解决吗，在nuxt2的时候不会这样子

### ISSUE THREAD

**Issue by Loser1027** [element-plus/element-plus-nuxt-starter#75]
![image](https://github.com/element-plus/element-plus-nuxt-starter/assets/40681039/8f30f0f1-c5aa-4050-8cef-c5a267bd6b94)
![image](https://github.com/element-plus/element-plus-nuxt-starter/assets/40681039/8d8f44c3-ad84-4ce7-b7d6-2578f8985e47)
![image](https://github.com/element-plus/element-plus-nuxt-starter/assets/40681039/38cee68e-9a11-4e69-baea-0230c55ab03d)
![image](https://github.com/element-plus/element-plus-nuxt-starter/assets/40681039/4e2b2cb4-0e2b-4c28-9f64-265fabd4ee78)

**Comment by wkl007** [comment]
有同样的问题。

**Comment by zndle** [comment]
试下这样：
```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  css: [
    '@/assets/scss/element.scss',
    '@/assets/scss/index.scss', // 这里就是你定义的样式
    '--other styles --',
  ],
  vite: {
    // css: {
    //   preprocessorOptions: {
    //     scss: {
    //       additionalData: `@use "@/assets/scss/element/index.scss" as element;`,
    //     },
    //   },
    // },
  },
  modules: ["@element-plus/nuxt"],
  elementPlus: {
    importStyle: false,  // 不用插件导入样式
  },
});
```
而在 `element.scss` 里，你可以这样写：
```scss
$-colors: (
    'primary': ('base': rgba(107, 33, 168, 1),
    ),
    'success': ('base': #67c23a,
    ),
    'warning': ('base': #e6a23c,
    ),
    'danger': ('base': #f56c6c,
    ),
    'error': ('base': #f56c6c,
    ),
    'info': ('base': #909399,
    ),
);

@forward 'element-plus/theme-chalk/src/common/var.scss' with ($colors: $-colors);

@import 'element-plus/theme-chalk/src/index.scss';
```

**Comment by yanhoor** [comment]
> 试下这样：
> 
> ```ts
> export default defineNuxtConfig({
>   devtools: { enabled: true },
>   css: [
>     '@/assets/scss/element.scss',
>     '@/assets/scss/index.scss', // 这里就是你定义的样式
>     '--other styles --',
>   ],
>   vite: {
>     // css: {
>     //   preprocessorOptions: {
>     //     scss: {
>     //       additionalData: `@use "@/assets/scss/element/index.scss" as element;`,
>     //     },
>     //   },
>     // },
>   },
>   modules: ["@element-plus/nuxt"],
>   elementPlus: {
>     importStyle: false,  // 不用插件导入样式
>   },
> });
> ```
> 
> 而在 `element.scss` 里，你可以这样写：
> 
> ```css-scss
> $-colors: (
>     'primary': ('base': rgba(107, 33, 168, 1),
>     ),
>     'success': ('base': #67c23a,
>     ),
>     'warning': ('base': #e6a23c,
>     ),
>     'danger': ('base': #f56c6c,
>     ),
>     'error': ('base': #f56c6c,
>     ),
>     'info': ('base': #909399,
>     ),
> );
> 
> @forward 'element-plus/theme-chalk/src/common/var.scss' with ($colors: $-colors);
> 
> @import 'element-plus/theme-chalk/src/index.scss';
> ```

这样引入全部样式然后怎么去掉未使用的样式呢，@fullhuman/postcss-purgecss 好像用不了

**Comment by zndle** [comment]
> > 试下这样：
> > ```ts
> > export default defineNuxtConfig({
> >   devtools: { enabled: true },
> >   css: [
> >     '@/assets/scss/element.scss',
> >     '@/assets/scss/index.scss', // 这里就是你定义的样式
> >     '--other styles --',
> >   ],
> >   vite: {
> >     // css: {
> >     //   preprocessorOptions: {
> >     //     scss: {
> >     //       additionalData: `@use "@/assets/scss/element/index.scss" as element;`,
> >     //     },
> >     //   },
> >     // },
> >   },
> >   modules: ["@element-plus/nuxt"],
> >   elementPlus: {
> >     importStyle: false,  // 不用插件导入样式
> >   },
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 而在 `element.scss` 里，你可以这样写：
> > ```
> > $-colors: (
> >     'primary': ('base': rgba(107, 33, 168, 1),
> >     ),
> >     'success': ('base': #67c23a,
> >     ),
> >     'warning': ('base': #e6a23c,
> >     ),
> >     'danger': ('base': #f56c6c,
> >     ),
> >     'error': ('base': #f56c6c,
> >     ),
> >     'info': ('base': #909399,
> >     ),
> > );
> > 
> > @forward 'element-plus/theme-chalk/src/common/var.scss' with ($colors: $-colors);
> > 
> > @import 'element-plus/theme-chalk/src/index.scss';
> > ```
> 
> 这样引入全部样式然后怎么去掉未使用的样式呢，@fullhuman/postcss-purgecss 好像用不了

...那这样：建一个 `BaseApp.vue` 的组件（刚好用来放置全局的 `<el-config-provider>`) ，用于包裹所有的 layouts 。然后就不要在 `nuxt.config.ts` 中引入样式。在它的 `<style>` 引入自定义的样式:

```
<!-- ... 其它内容....-->
<style lang="scss">
@import '~/assets/scss/custom.scss';

</style>
```
嘿嘿，办法总比困难多。

**Comment by yanhoor** [comment]
> > > 试下这样：
> > > ```ts
> > > export default defineNuxtConfig({
> > >   devtools: { enabled: true },
> > >   css: [
> > >     '@/assets/scss/element.scss',
> > >     '@/assets/scss/index.scss', // 这里就是你定义的样式
> > >     '--other styles --',
> > >   ],
> > >   vite: {
> > >     // css: {
> > >     //   preprocessorOptions: {
> > >     //     scss: {
> > >     //       additionalData: `@use "@/assets/scss/element/index.scss" as element;`,
> > >     //     },
> > >     //   },
> > >     // },
> > >   },
> > >   modules: ["@element-plus/nuxt"],
> > >   elementPlus: {
> > >     importStyle: false,  // 不用插件导入样式
> > >   },
> > > });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 而在 `element.scss` 里，你可以这样写：
> > > ```
> > > $-colors: (
> > >     'primary': ('base': rgba(107, 33, 168, 1),
> > >     ),
> > >     'success': ('base': #67c23a,
> > >     ),
> > >     'warning': ('base': #e6a23c,
> > >     ),
> > >     'danger': ('base': #f56c6c,
> > >     ),
> > >     'error': ('base': #f56c6c,
> > >     ),
> > >     'info': ('base': #909399,
> > >     ),
> > > );
> > > 
> > > @forward 'element-plus/theme-chalk/src/common/var.scss' with ($colors: $-colors);
> > > 
> > > @import 'element-plus/theme-chalk/src/index.scss';
> > > ```
> > 
> > 
> > 这样引入全部样式然后怎么去掉未使用的样式呢，@fullhuman/postcss-purgecss 好像用不了
> 
> ...那这样：建一个 `BaseApp.vue` 的组件（刚好用来放置全局的 `<el-config-provider>`) ，用于包裹所有的 layouts 。然后就不要在 `nuxt.config.ts` 中引入样式。在它的 `<style>` 引入自定义的样式:
> 
> ```
> 
> <style lang="scss">
> @import '~/assets/scss/custom.scss';
> 
> </style>
> ```
> 
> 嘿嘿，办法总比困难多。

这样就会有这个优先级的问题了

**Comment by zndle** [comment]
> > > > 试下这样：
> > > > ```ts
> > > > export default defineNuxtConfig({
> > > >   devtools: { enabled: true },
> > > >   css: [
> > > >     '@/assets/scss/element.scss',
> > > >     '@/assets/scss/index.scss', // 这里就是你定义的样式
> > > >     '--other styles --',
> > > >   ],
> > > >   vite: {
> > > >     // css: {
> > > >     //   preprocessorOptions: {
> > > >     //     scss: {
> > > >     //       additionalData: `@use "@/assets/scss/element/index.scss" as element;`,
> > > >     //     },
> > > >     //   },
> > > >     // },
> > > >   },
> > > >   modules: ["@element-plus/nuxt"],
> > > >   elementPlus: {
> > > >     importStyle: false,  // 不用插件导入样式
> > > >   },
> > > > });
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 而在 `element.scss` 里，你可以这样写：
> > > > ```
> > > > $-colors: (
> > > >     'primary': ('base': rgba(107, 33, 168, 1),
> > > >     ),
> > > >     'success': ('base': #67c23a,
> > > >     ),
> > > >     'warning': ('base': #e6a23c,
> > > >     ),
> > > >     'danger': ('base': #f56c6c,
> > > >     ),
> > > >     'error': ('base': #f56c6c,
> > > >     ),
> > > >     'info': ('base': #909399,
> > > >     ),
> > > > );
> > > > 
> > > > @forward 'element-plus/theme-chalk/src/common/var.scss' with ($colors: $-colors);
> > > > 
> > > > @import 'element-plus/theme-chalk/src/index.scss';
> > > > ```
> > > 
> > > 
> > > 这样引入全部样式然后怎么去掉未使用的样式呢，@fullhuman/postcss-purgecss 好像用不了
> > 
> > 
> > ...那这样：建一个 `BaseApp.vue` 的组件（刚好用来放置全局的 `<el-config-provider>`) ，用于包裹所有的 layouts 。然后就不要在 `nuxt.config.ts` 中引入样式。在它的 `<style>` 引入自定义的样式:
> > ```
> > 
> > <style lang="scss">
> > @import '~/assets/scss/custom.scss';
> > 
> > </style>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 嘿嘿，办法总比困难多。
> 
> 这样就会有这个优先级的问题了

那你把 Element-Plus 的静态CSS  copy一份过来。~ 既然用了@fullhuman/postcss-purgecss 来瘦身，那就没必要再CSS上按需加载了.

**Comment by YunYouJun** [comment]
看起来已经解决了，先关闭了。
如果有可复现的示例？可重新发起。
