### ISSUE TITLE
如何切换为中文

### ISSUE THREAD

**Issue by qiuhengyu** [element-plus/element-plus-nuxt-starter#76]
如何把page等组件用中文显示呢？

**Comment by Keystion** [comment]
```vue
<script setup lang="ts">

import zhCn from "element-plus/es/locale/lang/zh-cn";

</script>

<template>
  <el-config-provider :locale="zhCn">
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </el-config-provider>
</template>
```

`locale` 接收一个对象，多语言切换，写个映射即可。 

更多 `el-config-provider` 配置查看 [packages/components/config-provider/src/config-provider-props.ts](https://github.com/element-plus/element-plus/blob/dev/packages/components/config-provider/src/config-provider-props.ts)。

**Comment by YunYouJun** [comment]
https://element-plus.org/zh-CN/component/config-provider.html#i18n-%E9%85%8D%E7%BD%AE
